/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koneksi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import database.koneksidb;
import java.sql.*;
import javax.swing.JLabel;



public class DataMahasiswa extends javax.swing.JFrame {
    
    Connection koneksi = database.koneksidb.getkoneksidb();

        public DataMahasiswa() {
        initComponents();
    }
    
    
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    

    
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        namatext = new javax.swing.JTextField();
        npmtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jk = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/login logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 350, 600);
        jPanel1.add(namatext);
        namatext.setBounds(450, 160, 260, 40);
        jPanel1.add(npmtext);
        npmtext.setBounds(450, 230, 260, 40);

        jLabel2.setText("NPM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 200, 90, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Mahasiswa");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 60, 240, 40);

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 120, 90, 40);

        jLabel5.setText("Jenis kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 280, 90, 40);

        jButton1.setText("Kembali");
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 400, 74, 23);

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 470, 72, 23);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari);
        btnCari.setBounds(640, 400, 72, 23);

        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan", " " }));
        jPanel1.add(jk);
        jk.setBounds(450, 312, 260, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        login back = new login();
        back.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
   
        String nama = namatext.getText();
    String npm = npmtext.getText();
    String jenis_kelamin = jk.getSelectedItem().toString();
        
        if (nama.isEmpty() || npm.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi semua field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Membuat kueri SQL untuk mencari data
    String query = "SELECT * FROM kelas WHERE nama=? AND npm=? AND jenis_kelamin=?";

    try {
        // Mendapatkan koneksi dari kelas koneksidb
        Connection koneksi = database.koneksidb.getkoneksidb();
        PreparedStatement preparedStatement = koneksi.prepareStatement(query);

        // Mengatur parameter kueri sesuai dengan nilai dari form
        preparedStatement.setString(1, nama);
        preparedStatement.setString(2, npm);
        preparedStatement.setString(3, jenis_kelamin);

        // Mengeksekusi kueri dan mendapatkan hasil
        ResultSet resultSet = preparedStatement.executeQuery();

        // Menampilkan hasil pada tabel atau melakukan operasi lain sesuai kebutuhan Anda
        // Misalnya, menampilkan hasil pada JOptionPane
        if (resultSet.next()) {
            JOptionPane.showMessageDialog(this, "Data ditemukan!\nNama: " + resultSet.getString("nama")
                    + "\nNPM: " + resultSet.getString("npm")
                    + "\nJenis Kelamin: " + resultSet.getString("jenis_kelamin"), "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int option = JOptionPane.showConfirmDialog(this, "Data tidak ditemukan. Apakah Anda ingin mencoba lagi?", "Informasi", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Mengosongkan kolom pencarian
                namatext.setText("");
                npmtext.setText("");
                // Atau dapat memberikan fokus kembali ke kolom nama
                // txtNama.requestFocus();
            }
        }

        // Menutup koneksi dan resource yang digunakan
        resultSet.close();
        preparedStatement.close();
        koneksi.close();
    } catch (SQLException e) {
        
        displayErrorMessage("Terjadi kesalahan dalam menjalankan kueri SQL!");
        e.printStackTrace();
        clearErrorMessage();
        
    }
    
    }
    
    private void displayErrorMessage(String message) {
    JOptionPane.showMessageDialog(this, message, "Kesalahan", JOptionPane.ERROR_MESSAGE);
}

// Metode untuk membersihkan pesan kesalahan
private void clearErrorMessage() {
    // Membersihkan pesan kesalahan jika ada
    JOptionPane.getRootFrame().dispose();
}
    

    // ...

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new DataMahasiswa().setVisible(true);
        });
    
    /**
    }//GEN-LAST:event_btnCariActionPerformed

     * @param args the command line arguments
     */
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JTextField namatext;
    private javax.swing.JTextField npmtext;
    // End of variables declaration//GEN-END:variables
}
